services:
  ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - RUBY_VERSION
        - DUCKDB_VERSION
    working_dir: /root/ruby-duckdb
    volumes:
      - .:/root/ruby-duckdb
