name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        ruby: ['3.2.9', '3.3.10', '3.4.9', '4.0.2', 'head']
        duckdb: ['1.4.4', '1.5.0']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: duckdb cache
      id: duckdb-cache
      uses: actions/cache@v4
      with:
        path: libduckdb-linux-amd64
        key: ${{ runner.os }}-duckdb-v${{ matrix.duckdb }}

    - name: Download duckdb ${{ matrix.duckdb }}
      if: steps.duckdb-cache.outputs.cache-hit != 'true'
      env:
        DUCKDB_VERSION: ${{ matrix.duckdb }}
      run: |
        curl -OL https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip
        mkdir libduckdb-linux-amd64
        unzip libduckdb-linux-amd64.zip -d libduckdb-linux-amd64

    - name: setup libduckdb.so
      run: |
        sudo cp libduckdb-linux-amd64/libduckdb.so /usr/local/lib/
        sudo ldconfig

    - name: bundle install with Ruby ${{ matrix.ruby }}
      run: |
        bundle install --jobs 4 --retry 3

    - name: Build test with DUCKDB_API_NO_DEPRECATED and Ruby ${{ matrix.ruby }}
      run: |
        env DUCKDB_API_NO_DEPRECATED=1 bundle exec rake build -- --with-duckdb-include=${GITHUB_WORKSPACE}/libduckdb-linux-amd64 --with-duckdb-lib=${GITHUB_WORKSPACE}/libduckdb-linux-amd64
        bundle exec rake clean

    - name: Build with Ruby ${{ matrix.ruby }}
      run: |
        bundle exec rake build -- --with-duckdb-include=${GITHUB_WORKSPACE}/libduckdb-linux-amd64 --with-duckdb-lib=${GITHUB_WORKSPACE}/libduckdb-linux-amd64

    - name: confirm duckdb library version
      run: |
        ruby -Ilib -rduckdb -e 'puts "duckdb library #{DuckDB.library_version}"'

    - name: test with Ruby ${{ matrix.ruby }}
      env:
        MYSQL_TEST: 1
      run: |
        env RUBYOPT=-W:deprecated rake test

  post-test:
    name: All tests passed on Ubuntu
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ok
